### ISSUE TITLE
Add description on how to set API key per style

### ISSUE THREAD

**Issue by nvkelso** [tangrams/cartography-docs#2]
Most the styles must be updated to allow this, though.

**Question:** /cc @bcamper 

* Should Mapzen house styles styles continue to ship with Mapzen's API keys set or leave that blank? 

If we remove it, then our product pages would need to set them on map init, and the Github repo index pages would also need to set them on init.

**Comment by nvkelso** [comment]
Confirmed this approach with Brett:

**Using Tangram's JS API:**

```
    var layer = Tangram.leafletLayer({
        scene: { import: style_file, global: { sdk_mapzen_api_key: 'mapzen-xxxxxx' } },
        attribution: '<a href="https://mapzen.com/tangram" target="_blank">Tangram</a> | &copy; OSM contributors | <a href="https://mapzen.com/" target="_blank">Mapzen</a>'
    });
```

**The house style YAML files would change something like:**

```
global:
    # Sign up for a Mapzen API key to enjoy higher rate limits
    # https://mapzen.com/documentation/overview/#developer-accounts-and-api-keys
    sdk_mapzen_api_key: ''     # set this value to your Mapzen API key

sources:
    mapzen:
        type: MVT
        url:  https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.mvt
        max_zoom: 16
        url_params:
            api_key: global.sdk_mapzen_api_key
    normals:
        type: Raster
        url: https://tile.mapzen.com/mapzen/terrain/v1/normal/{z}/{x}/{y}.png
        max_zoom: 15
        url_params:
            api_key: global.sdk_mapzen_api_key
```

(updated 2016.12.22 and again 2017.01.05)
